import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hats Protocol Discord Gating</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <p>Hats Protocol Discord Gating</p>
        </main>
      </div>
    </>
  );
}
